const API_SERVER_CARS = "http://localhost:8091"
const API_SERVER_PAYMENTS = "http://localhost:8092"
const API_SERVER_REQUESTS = "http://localhost:8093"
const API_SERVER_USERS = "http://localhost:8094"
const STATUS_PENDING = 0;
const STATUS_DENIED = 1;
const STATUS_ACTIVE = 3;
const STATUS_REPAIR_NEEDED = 4;
const STATUS_ENDED = 5;

export { API_SERVER_CARS, API_SERVER_USERS, API_SERVER_REQUESTS, API_SERVER_PAYMENTS, STATUS_ENDED, STATUS_REPAIR_NEEDED, STATUS_ACTIVE, STATUS_DENIED, STATUS_PENDING };
