spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oop2
    username: 'oop'
    password: ''
  liquibase:
    change-log: classpath:/db/changelog/db.changeLog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: core

logging:
  level:
    liquibase: INFO


keycloak:
  authServerUrl: http://localhost:8080/auth
  realm: master
  resource: payments-microservice
  public-client: true
  ssl-required: "none"

keycloak-auth:
  clientSecret: 3020f39b-1370-4ecd-a373-43b231b5d3ab
  adminUsername: admin
  adminPassword: admin